name: "pr"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: |
          npm ci
          npm run build
          npm run format-check
          npm run lint
          npm run package
          npm run test

      - name: Check for changes
        id: diff
        continue-on-error: true
        run: git diff --quiet dist

  self-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: docker build
        id: build
        uses: ./
        with:
          file: __tests__/Dockerfile
          repository: 624762752008.dkr.ecr.eu-west-1.amazonaws.com/theros-base/actions-docker
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}

      - name: Check that push worked
        run: |
          docker pull ${{ steps.build.outputs.image }}

  self-check-custom-tag:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: docker build
        id: build
        uses: ./
        with:
          file: __tests__/Dockerfile
          skip-default-tag: true
          repository: 624762752008.dkr.ecr.eu-west-1.amazonaws.com/theros-base/actions-docker-custom
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          tags: |
            624762752008.dkr.ecr.eu-west-1.amazonaws.com/theros-base/actions-docker-custom:my-tag-${{ github.event.pull_request.head.sha }}

      - name: Check that push worked
        run: |
          docker pull ${{ steps.build.outputs.image }}

      - name: Check that skip works
        run: |
          if docker pull 624762752008.dkr.ecr.eu-west-1.amazonaws.com/theros-base/actions-docker-custom:${{ github.event.pull_request.head.sha }}; then
            echo "Tag found while expected to be missing";
            exit 1;
          fi;
          echo "Confirmed: Default tag not found"

          semantic-release:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
                with:
                  fetch-depth: 0
              - name: Dry-run release
                uses: theros-org/actions-semantic-release@v1
                id: semantic-release
                with:
                  dry_run: true
                  check_name: Semantic release
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              - name: Lint commit messages
                uses: theros-org/commitlint-github-action@v5

